### ISSUE TITLE
Trouble pulling "solar surplus" in kwh

### ISSUE THREAD

**Issue by jherby2k** [gtdiehl/iotawattpy#4]
Pardon the double-post... i'm not sure if this is an API issue or with the integration. i'm having a terrible time getting a "Solar Surplus" output showing up in HA.

Basically HA seems to want a "return to grid" sensor rather than just looking at negative grid_total values (which would make more sense to me, but whatever). So i created an output called "Solar_Surplus" that looks like this:

Watts = 0 max (-1 x (Main_1 + Main_2))

(alternately, also tried this:)

Watts = 0 max (0 - main_1 - main_2)

The wattage sensor works just fine, but I get 0 kwh for the _kw version. It also appears to never refresh until an HA restart.

FYI, my Grid_Consumed output works just fine, with

Watts = 0 max (Main_1 + Main_2)

Any suggestions? On the Iotawatt itself using the Graph+ UI, i can see these guys no problem in WH over a year, month etc.

**Comment by gtdiehl** [comment]
@jherby2k I was thinking because you mentioned that upon HA restart the kWh value is shown, that the API is probably returning the correct value to HA but just in case can you run the example script?

Then when you see the kWh value in HA is the value seen on the Energy view or the Developer Tools view? 

The Developer view should be updating the sensor state every 30seconds. The Energy view I'm not too sure how often it updates as it says it may take 2 hours to start showing data.

If the Developer view is not updating then it's probably in the Iotawatt sensor integration code.

**Comment by jherby2k** [comment]
Seems to be an issue with Iotawatt itself, as per our other discussion. i'll close this
